#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[System.Data.Linq.Mapping.DatabaseAttribute(Name="AnhVan10")]
public partial class AV10DataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertVOCABULARY(VOCABULARY instance);
  partial void UpdateVOCABULARY(VOCABULARY instance);
  partial void DeleteVOCABULARY(VOCABULARY instance);
  #endregion
	
	public AV10DataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AnhVan10ConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public AV10DataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public AV10DataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public AV10DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public AV10DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<VOCABULARY> VOCABULARies
	{
		get
		{
			return this.GetTable<VOCABULARY>();
		}
	}
}

[Table(Name="dbo.VOCABULARY")]
public partial class VOCABULARY : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID_Voc;
	
	private System.Nullable<int> _ID_Unit;
	
	private System.Nullable<int> _ID_Skill;
	
	private string _Eword;
	
	private string _Vword;
	
	private string _Voice_Path;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_VocChanging(int value);
    partial void OnID_VocChanged();
    partial void OnID_UnitChanging(System.Nullable<int> value);
    partial void OnID_UnitChanged();
    partial void OnID_SkillChanging(System.Nullable<int> value);
    partial void OnID_SkillChanged();
    partial void OnEwordChanging(string value);
    partial void OnEwordChanged();
    partial void OnVwordChanging(string value);
    partial void OnVwordChanged();
    partial void OnVoice_PathChanging(string value);
    partial void OnVoice_PathChanged();
    #endregion
	
	public VOCABULARY()
	{
		OnCreated();
	}
	
	[Column(Storage="_ID_Voc", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int ID_Voc
	{
		get
		{
			return this._ID_Voc;
		}
		set
		{
			if ((this._ID_Voc != value))
			{
				this.OnID_VocChanging(value);
				this.SendPropertyChanging();
				this._ID_Voc = value;
				this.SendPropertyChanged("ID_Voc");
				this.OnID_VocChanged();
			}
		}
	}
	
	[Column(Storage="_ID_Unit", DbType="Int")]
	public System.Nullable<int> ID_Unit
	{
		get
		{
			return this._ID_Unit;
		}
		set
		{
			if ((this._ID_Unit != value))
			{
				this.OnID_UnitChanging(value);
				this.SendPropertyChanging();
				this._ID_Unit = value;
				this.SendPropertyChanged("ID_Unit");
				this.OnID_UnitChanged();
			}
		}
	}
	
	[Column(Storage="_ID_Skill", DbType="Int")]
	public System.Nullable<int> ID_Skill
	{
		get
		{
			return this._ID_Skill;
		}
		set
		{
			if ((this._ID_Skill != value))
			{
				this.OnID_SkillChanging(value);
				this.SendPropertyChanging();
				this._ID_Skill = value;
				this.SendPropertyChanged("ID_Skill");
				this.OnID_SkillChanged();
			}
		}
	}
	
	[Column(Storage="_Eword", DbType="NVarChar(20)")]
	public string Eword
	{
		get
		{
			return this._Eword;
		}
		set
		{
			if ((this._Eword != value))
			{
				this.OnEwordChanging(value);
				this.SendPropertyChanging();
				this._Eword = value;
				this.SendPropertyChanged("Eword");
				this.OnEwordChanged();
			}
		}
	}
	
	[Column(Storage="_Vword", DbType="NVarChar(20)")]
	public string Vword
	{
		get
		{
			return this._Vword;
		}
		set
		{
			if ((this._Vword != value))
			{
				this.OnVwordChanging(value);
				this.SendPropertyChanging();
				this._Vword = value;
				this.SendPropertyChanged("Vword");
				this.OnVwordChanged();
			}
		}
	}
	
	[Column(Storage="_Voice_Path", DbType="NVarChar(50)")]
	public string Voice_Path
	{
		get
		{
			return this._Voice_Path;
		}
		set
		{
			if ((this._Voice_Path != value))
			{
				this.OnVoice_PathChanging(value);
				this.SendPropertyChanging();
				this._Voice_Path = value;
				this.SendPropertyChanged("Voice_Path");
				this.OnVoice_PathChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
